### PR TITLE
Added audioStreamFormat and audioTrackFormat bypass for audioTrackUID…

### PR DESCRIPTION
**Pull request by davemar-bbc**
Added audioStreamFormat and audioTrackFormat bypass for audioTrackUID and CHNA chunk. So audioChannelFormat can be referenced directly for PCM instead. This matches up with BS.2076-2.

Where audioTrackFormatIDRefs would have been non-optional in the past, they now have to be optional as they could be replaced by audioChannelFormatIDRefs instead.

### CODE REVIEW

**Comment by davemar-bbc** [comment]
I'll fix these test fails.

**Comment by tomjnixon** [comment]
Thanks. As for the general approach I'd be tempted to just have one field in the CHNA structure (AudioID), which should simplify things a bit. There's still only one field in the CHNA called trackRef, and that's what we decided to do for libbw64.

We should check that the rendering item selection code rejects uses of this for now, hopefully with a sensible error message. Eventually we'd want to update this to work properly; I'll have a think about how that should work.

**Comment by davemar-bbc** [comment]
Does libadm carry both audioTrackFormat and audioChannelFormat refs in audioTrackUID, or does it use trackRef like the CHNA does in libbw64?

**Comment by tomjnixon** [comment]
Both, or at least it will once the -2 changes are done. I think that makes sense here too, to keep a good correspondence between the ADM and the EAR data structures.

**Comment by tomjnixon** [comment]
This was merged as part of the -2 work -- thanks!

**Pull request closed without merging**
