### PR TITLE
reworked loudness metadata

### PR DESCRIPTION
**Pull request by tomjnixon**
Same as #20, but turns loudnessMetadata into list

Closes #20

### CODE REVIEW

**Comment by kickermeister** [comment]
Enabling multiple loudnessMetadata subelements makes perfect sense. In my original attempt in #20 I overlooked the quantity column completely. I was wondering, however, whether it would make sense to update the test(s) for loudnessMetadata to cover also multiple subelements? Currently, the test fails when adding another but I didn't have a good spontaneous idea how to make a simple change for that case.

**Comment by tomjnixon** [comment]
Thanks, that's a good point. I've added a test with multiple elements, generated inside the test as `base.xml` would be mostly loudness metadata otherwise.

**Comment by kickermeister** [comment]
Great, thank you. I think it good to go now!

**Comment by tomjnixon** [comment]
Merged, thanks!

**Pull request closed without merging**
